name: Internship Bot Runner and Deployer

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours — change to */6 for 6-hour interval
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install chromium

      - name: Run Internship Bot
        run: python run_automation.py
        env:
          # AI API Keys
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

          # Job Platform Credentials
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
          INTERNSHALA_EMAIL: ${{ secrets.INTERNSHALA_EMAIL }}
          INTERNSHALA_PASSWORD: ${{ secrets.INTERNSHALA_PASSWORD }}
          INDEED_EMAIL: ${{ secrets.INDEED_EMAIL }}
          INDEED_PASSWORD: ${{ secrets.INDEED_PASSWORD }}

          # Application Settings
          SIMILARITY_THRESHOLD: ${{ secrets.SIMILARITY_THRESHOLD }}
          APPLICATION_DELAY: ${{ secrets.APPLICATION_DELAY }}
          MAX_APPLICATIONS_PER_DAY: ${{ secrets.MAX_APPLICATIONS_PER_DAY }}

          # Logging
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          LOG_FILE: auto_run.log

          # Email Notification Settings
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_MAX_RETRIES: ${{ secrets.EMAIL_MAX_RETRIES }}
          EMAIL_RETRY_DELAY: ${{ secrets.EMAIL_RETRY_DELAY }}
          EMAIL_NOTIFICATIONS_ENABLED: "true"

      # Optional: Deploy logs/output to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()  # Only run if bot executes successfully
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}  # Make sure secret exists
          publish_dir: ./output  # Set this to the correct output/log directory
